# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('patient_bmi', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='DiastolicBloodPressure',
            fields=[
                ('patient_dbp', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('patient_hr', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=140)),
                ('patient_sex', models.CharField(max_length=140)),
                ('patient_dob', models.DateField()),
                ('patient_contact', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystolicBloodPressure',
            fields=[
                ('patient_sbp', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('patient_weight', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
    ]
